/*
 * router.h
 *
 *  Created on: 30 мая 2018 г.
 *      Author: developer
 */

#ifndef APPS_GRANUM_GRANUM_ROUTER_H_
#define APPS_GRANUM_GRANUM_ROUTER_H_

#include <nuttx/fs/fs.h>

extern int nrf_fd;
extern int file_fd;
extern int fifo_fd;
extern int raspberry_fd;

#define ROUTE_EXITPOINT_CONTROLFLOW	(1 << 0)
#define ROUTE_EXITPOINT_SDCARD		(1 << 1)
#define ROUTE_EXITPOINT_RADIO		(1 << 2)
#define ROUTE_EXITPOINT_RASPBERRY	(1 << 3)

#define ROUTE_WAY_FROMCONTROLFLOW		( ROUTE_EXITPOINT_SDCARD | ROUTE_EXITPOINT_RADIO | ROUTE_EXITPOINT_RASPBERRY )
#define ROUTE_WAY_TELEMETRY_COMMON		( ROUTE_EXITPOINT_CONTROLFLOW | ROUTE_EXITPOINT_SDCARD | ROUTE_EXITPOINT_RADIO | ROUTE_EXITPOINT_RASPBERRY )
#define ROUTE_WAY_TELEMETRY_RASPBERRY	( ROUTE_EXITPOINT_RADIO | ROUTE_EXITPOINT_SDCARD | ROUTE_EXITPOINT_RADIO )
#define ROUTE_WAY_GROUND_COMMANDS		( ROUTE_EXITPOINT_CONTROLFLOW | ROUTE_EXITPOINT_SDCARD )

#define ROUTE(WAY, POINTER, LENGTH) \
	if(WAY & ROUTE_EXITPOINT_CONTROLFLOW) write(fifo_fd, POINTER, LENGTH);\
	if(WAY & ROUTE_EXITPOINT_SDCARD) write(file_fd, POINTER, LENGTH); fsync(file_fd);\
	if(WAY & ROUTE_EXITPOINT_RADIO) write(nrf_fd, POINTER, LENGTH);\
	if(WAY & ROUTE_EXITPOINT_RASPBERRY) write(raspberry_fd, POINTER, LENGTH);

#endif /* APPS_GRANUM_GRANUM_ROUTER_H_ */
